// pages/characters/index.tsx
import { CharacterCard } from "@/components/cards/CharacterCard";
import { Container } from "@/components/Container";
import { Layout } from "@/components/Layout";
import { charactersArray } from "@/data/characters";
import { NextPage } from "next";

const CharactersIndex: NextPage = () => {
  return (
    <Layout title="Characters" description="Genshin Impact playable characters.">
      <Container>
        <h1 className="font-semibold text-4xl mb-4 mt-6">Characters</h1>

        <div className="flex flex-row flex-wrap gap-2 justify-evenly md:justify-start">
          {charactersArray.map((character) => (
            <CharacterCard
              key={character.id}
              id={character.id}
              name={character.name}
              rarity={character.rarity}
            />
          ))}
        </div>
      </Container>
    </Layout>
  );
};

export default CharactersIndex;

// pages/characters/index.vue
<template>
  <MainContainer>
    <h1 class="font-semibold text-4xl mb-4 mt-6">Characters</h1>

    <div class="flex flex-row flex-wrap gap-2 justify-evenly md:justify-start">
      <CharacterCard
        v-for="character in charactersArray"
        :key="character.id"
        :id="character.id"
        :name="character.name"
        :rarity="character.rarity"
      />
    </div>
  </MainContainer>
</template>

<script setup lang="ts">
import { charactersArray } from "@/data/characters";
</script>
