// pages/guides/index.vue
<template>
  <MainContainer>
    <input
      v-model="search"
      type="text"
      placeholder="Search by title"
      class="w-full mb-4 lg:mb-8 leading-6 dark:text-neutral-300 placeholder:text-neutral-600 accent-primary-500 rounded-md ring-1 bg-white dark:bg-neutral-800 ring-neutral-900/10 dark:ring-neutral-50/10 shadow-sm py-1.5 pl-2 pr-3"
    />

    <div
      class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-4"
    >
      <CardsGuide
        v-for="c in publishedCharacters"
        v-show="isShown(c.name)"
        :id="c.id"
        :key="c.id"
        :to="`/guides/${c.id}`"
        :title="c.name"
        :thumbnail="`/img/characters/${c.id}/avatar_header.webp`"
        :description="c.description"
      />
    </div>
  </MainContainer>
</template>

<script setup lang="ts">
import { computed, ref, watch } from "vue";
import { debouncedRef } from "@vueuse/core";

import { charactersArray } from "@/data/characters";
import published from "@/data/guides/compiled/characters/published.json";
import { BeakerIcon } from "@heroicons/vue/outline";

definePageMeta({
  name: `Guides`,
  icon: BeakerIcon,
  navbar: true,
});

const router = useRouter();
const route = useRoute();

const publishedCharacters = computed(() => {
  return charactersArray.filter(({ id }) => published.includes(id));
});

const search = ref(route.query.q?.toString() ?? ``);
const debouncedSearch = debouncedRef(search, 300);

watch(debouncedSearch, () => {
  router.push({ query: { q: search.value } });
});

const isShown = (title: string) => {
  return title.toLowerCase().includes(debouncedSearch.value.toLowerCase());
};

useZenlessMeta({
  title: `Guides`,
  description: `Various playstyle and build guides for Genshin Impact characters`,
});
</script>

// src/pages/guides/index.tsx
import type { NextPage } from "next";
import type { ChangeEvent } from "react";

import { debounce, isEmpty } from "lodash-es";
import { useEffect, useRef } from "react";

import { GuideCard } from "@/components/cards/GuideCard";
import { Container } from "@/components/Container";
import { Input } from "@/components/Input";
import { Layout } from "@/components/Layout";
import { charactersArray } from "@/data/characters";
import published from "@/data/guides/compiled/characters/published.json";
import { useRouterReady } from "@/hooks/useRouterReady";

// this doesn't need to be reactive
const publishedCharacters = charactersArray.filter(({ id }) => published.includes(id));

const GuidesIndex: NextPage = () => {
  const [ready, router] = useRouterReady();

  const inputRef = useRef<HTMLInputElement>(null);
  const q = router.query.q?.toString() ?? ``;

  const handleChange = debounce((e: ChangeEvent<HTMLInputElement>) => {
    const url = !isEmpty(e.target.value) ? `/guides?q=${e.target.value}` : `/guides`;
    void router.replace(url, undefined, { shallow: true });
  }, 300);

  useEffect(() => {
    const el = inputRef.current;
    if (el) {
      el.value = q;
    }
  }, [ready, q]);

  return (
    <Layout title="Guides" description="Genshin Impact characters' playstyle, builds and etc.">
      <Container>
        {ready && (
          <>
            <Input ref={inputRef} placeholder="Search by title" onChange={handleChange} fullWidth />

            <div className="columns-1 sm:columns-2 lg:columns-3 xl:columns-4 2xl:columns-5 gap-4 space-y-4">
              {publishedCharacters
                .filter((c) => c.id.includes(q.toString().toLowerCase()))
                .map((character) => (
                  <GuideCard
                    key={character.id}
                    id={character.id}
                    href={`/guides/${character.id}`}
                    title={character.name}
                    description={character.description}
                    thumbnail={`/img/characters/${character.id}/avatar_header.webp`}
                  />
                ))}
            </div>
          </>
        )}
      </Container>
    </Layout>
  );
};

export default GuidesIndex;
