// src/components/cards/GuideCard.tsx
import type { FC } from "react";

import dayjs from "dayjs";
import NextLink from "next/link";
import { useEffect, useState } from "react";

import { StaticPicture } from "@/components/StaticPicture";

interface Props {
  id: string;
  title: string;
  description?: string;
  publishedAt?: Date;
  thumbnail?: string;
  href?: string;
  className?: string;
}

export const GuideCard: FC<Props> = ({
  id,
  title,
  description,
  publishedAt,
  thumbnail,
  href = "#",
  className = "",
}) => {
  const [isMounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <NextLink href={href} prefetch={false}>
      <a id={id} className={`card card-vertical ${className}`}>
        {thumbnail && (
          <StaticPicture
            src={thumbnail}
            className="aspect-[9/16] min-h-[10rem] w-full rounded-t-lg object-fill object-top lg:min-h-[20rem]"
            alt="character icon"
          />
        )}

        <div className="p-4">
          {publishedAt && (
            <div className="text-sm font-medium text-primary-500">
              {isMounted && <>{dayjs(publishedAt).format("lll")}</>}
            </div>
          )}

          <p className="mb-2 block text-lg font-bold text-[#000] dark:text-dark-300">{title}</p>

          {description && <p className="text-justify text-sm">{description}</p>}
        </div>
      </a>
    </NextLink>
  );
};

// src/components/Cards/GuideCard.vue
<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts">
import { isString } from "lodash-es";
import { computed, h } from "vue";
import { RouterLink } from "vue-router";

interface Props {
  title: string;
  description?: string;
  publishedAt?: Date;
  thumbnail?: string;
  to?: string;
}

const props = withDefaults(defineProps<Props>(), {});

const rootComponent = computed(() => (isString(props.to) ? RouterLink : h("div")));
const rootProps = computed(() => (isString(props.to) ? { to: props.to } : {}));
</script>

<template>
  <component
    :is="rootComponent"
    v-bind="rootProps"
    class="flex flex-col text-neutral-900 dark:text-neutral-300 bg-neutral-100 dark:bg-dark-850 border border-neutral-200 dark:border-neutral-200/10 rounded-lg"
  >
    <div class="min-h-[10rem] lg:min-h-[20rem] w-full aspect-[9/16]">
      <img
        v-if="!!thumbnail"
        :src="thumbnail"
        loading="lazy"
        class="object-fill object-top rounded-t-lg"
      />
    </div>
    <div class="px-6 py-4 space-y-2">
      <div v-if="!!publishedAt" class="font-medium text-sm leading-6 text-primary-500">
        {{ $dayjs(publishedAt).format("HH:mm on DD.MM.YYYY") }}
      </div>
      <p class="block font-semibold text-base leading-6">
        {{ title }}
      </p>
      <p v-if="!!description" class="text-sm text-justify leading-6">
        {{ description }}
      </p>
    </div>
  </component>
</template>
