// components/cards/GuideCard.tsx
import { FC, useEffect, useState } from "react";
import NextLink from "next/link";
import dayjs from "dayjs";

interface Props {
  title: string;
  description?: string;
  publishedAt?: Date;
  thumbnail?: string;
  href?: string;
  className?: string;
}

export const GuideCard: FC<Props> = ({
  title,
  description,
  publishedAt,
  thumbnail,
  href = "#",
  className = "",
}) => {
  const [isMounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <NextLink href={href}>
      <a className={`card card-vertical ${className}`}>
        {thumbnail && (
          <img
            src={thumbnail}
            loading="lazy"
            className="card-thumbnail min-h-[10rem] lg:min-h-[20rem] aspect-[9/16]"
          />
        )}

        <div className="card-text-container">
          {publishedAt && (
            <div className="card-text-container-item font-medium text-sm leading-6 text-primary-500">
              {isMounted && <>{dayjs(publishedAt).format("lll")}</>}
            </div>
          )}

          <p className="card-text-container-item block font-semibold text-base leading-6">
            {title}
          </p>

          {description && (
            <p className="card-text-container-item text-sm text-justify leading-6">{description}</p>
          )}
        </div>
      </a>
    </NextLink>
  );
};

// src/components/Cards/GuideCard.vue
<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts">
import { RouterLink } from "vue-router";

interface Props {
  title: string;
  description?: string;
  publishedAt?: Date;
  thumbnail?: string;
  to?: {
    name: string;
    params: {
      id: string;
    };
  };
}

withDefaults(defineProps<Props>(), {});
</script>

<template>
  <RouterLink :to="to ?? '#'" class="card card-vertical">
    <img
      v-if="!!thumbnail"
      :src="thumbnail"
      loading="lazy"
      class="card-thumbnail min-h-[10rem] lg:min-h-[20rem] aspect-[9/16]"
    />

    <div class="card-text-container">
      <div
        v-if="!!publishedAt"
        class="card-text-container-item font-medium text-sm leading-6 text-primary-500"
      >
        {{ $dayjs(publishedAt).format("lll") }}
      </div>

      <p class="card-text-container-item block font-semibold text-base leading-6">
        {{ title }}
      </p>

      <p v-if="!!description" class="card-text-container-item text-sm text-justify leading-6">
        {{ description }}
      </p>
    </div>
  </RouterLink>
</template>
