// src/components/Navigation.tsx
import type { FC, SVGProps } from "react";

import { BeakerIcon, CalculatorIcon, HomeIcon, StarIcon } from "@heroicons/react/outline";
import { SunIcon, MoonIcon } from "@heroicons/react/solid";
import { useTheme } from "next-themes";
import NextLink from "next/link";
import { useRouter } from "next/router";
import { Fragment, useEffect, useState, useCallback } from "react";

type TIcon = (props: SVGProps<SVGSVGElement>) => JSX.Element;

interface NavRoute {
  path: string;
  title: string;
  hasNested?: boolean;
  Icon: TIcon;
}

const navRoutes: NavRoute[] = [
  {
    path: "/",
    title: "Home",
    Icon: HomeIcon,
  },
  {
    path: "/characters",
    title: "Characters",
    hasNested: true,
    Icon: StarIcon,
  },
  {
    path: "/guides",
    title: "Guides",
    hasNested: true,
    Icon: BeakerIcon,
  },
  {
    path: "/calc",
    title: "Calculator",
    Icon: CalculatorIcon,
  },
];

export const Navigation: FC = () => {
  const router = useRouter();

  const [isMounted, setMounted] = useState(false);
  const { theme, setTheme, resolvedTheme } = useTheme();

  const toggleDark = () => {
    // don't do anything unless it's client side
    if (!isMounted) return;

    if (resolvedTheme === "dark" && theme === "system") {
      setTheme("light");
    } else if (resolvedTheme === "light" && theme === "system") {
      setTheme("dark");
    } else {
      setTheme("system");
    }
  };

  useEffect(() => {
    setMounted(true);
  }, []);

  const isActive = useCallback(
    (navRoute: Omit<NavRoute, "Icon">) => {
      if (navRoute.hasNested === true) {
        return router.route.startsWith(navRoute.path);
      }

      return router.route === navRoute.path;
    },
    [router.route],
  );

  const activeClass = useCallback(
    (navRoute: Omit<NavRoute, "Icon">, isMobile = false) => {
      const active = isActive(navRoute);

      if (isMobile && active) {
        return "text-primary-500 dark:text-primary-400 font-bold";
      } else if (!isMobile && active) {
        return " !bg-primary-500 rounded-lg text-white";
      }

      return "";
    },
    [isActive],
  );

  return (
    <>
      {/* Mobile Bottom Navbar */}
      <nav className="z-10 lg:hidden fixed bottom-0 left-0 h-[var(--mobile-navbar-height)] w-full border-t border-neutral-200 dark:border-dark-200/10 dark:bg-dark-800 bg-white select-none">
        <div className="dark:text-slate-400 flex flex-row h-full gap-4 px-4 justify-between overflow-y-auto">
          {navRoutes.map(({ Icon, ...navRoute }) => (
            <NextLink key={`mobile-navbar-${navRoute.path}`} href={navRoute.path}>
              <a
                className={`${activeClass(
                  navRoute,
                  true,
                )} flex-1 flex flex-col items-center justify-center`}
              >
                <Icon className="h-6 w-6 p-0" />
                <h1 className="text-sm font-semibold">{navRoute.title}</h1>
              </a>
            </NextLink>
          ))}

          {isMounted && (
            <div
              onClick={toggleDark}
              className="flex-1 flex flex-col items-center justify-center cursor-pointer"
            >
              {resolvedTheme === "dark" && <SunIcon className="w-6 h-6" />}
              {resolvedTheme !== "dark" && <MoonIcon className="w-6 h-6" />}
              <h1 className="text-sm font-semibold">
                {resolvedTheme === "dark" && "Light"}
                {resolvedTheme !== "dark" && "Dark"}
              </h1>
            </div>
          )}
        </div>
      </nav>

      {/* Desktop Sidebard */}
      <aside
        data-description="Desktop Sidebar Navigation"
        className="sidebar sticky top-0 hidden lg:flex flex-col min-h-screen max-h-screen"
      >
        <div className="overflow-y-auto ml-4 my-4 w-64 h-full rounded-lg border border-neutral-200 dark:border-dark-200/10 dark:bg-dark-800 bg-white">
          <div className="flex flex-col gap-y-2 p-4 w-full">
            <div className="self-center py-4 mb-2 border-b border-neutral-200 dark:border-dark-200/10">
              <h1 className="font-extrabold text-xl">GENSHIN.ZENLESS</h1>
            </div>

            {navRoutes.map(({ Icon, ...navRoute }) => (
              <NextLink key={navRoute.path} href={navRoute.path}>
                <a
                  className={
                    "w-full flex flex-row items-center gap-x-2 px-3 py-2 font-semibold text-lg cursor-pointer" +
                    activeClass(navRoute)
                  }
                >
                  <Fragment>
                    <Icon className="h-7 w-7 p-0" />
                  </Fragment>
                  <h1>{navRoute.title}</h1>
                </a>
              </NextLink>
            ))}
          </div>

          {isMounted && (
            <div className="fixed bottom-8 left-8">
              <div
                onClick={() => toggleDark()}
                className="transition-all duration-75 bg-neutral-100 dark:bg-dark-900 dark:text-dark-300 outline outline-1 outline-neutral-200 dark:outline-dark-200/10 rounded-lg flex items-center justify-center aspect-square h-8 cursor-pointer"
              >
                {resolvedTheme === "dark" && <SunIcon className="w-5 h-5" />}
                {resolvedTheme !== "dark" && <MoonIcon className="w-5 h-5" />}
              </div>
            </div>
          )}
        </div>
      </aside>
    </>
  );
};

// components/Navigation.vue
<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts">
import { computed, ref } from "vue";

import { MenuIcon, XIcon } from "@heroicons/vue/outline";
import { MoonIcon, SunIcon } from "@heroicons/vue/solid";
import { onClickOutside } from "@vueuse/core";
import { useDark, useToggle } from "@vueuse/core";

const router = useRouter();

const isOpen = ref(false);
const popover = ref(null);

const isDark = useDark({ storageKey: "theme" });
const toggleDark = useToggle(isDark);

onClickOutside(popover, () => {
  isOpen.value = false;
});

// thanks firefox for being great
const firefoxMarginBottomClass = computed(() => {
  if (navigator.userAgent.toLowerCase().includes("firefox")) {
    return "mb-10";
  }
  return "mb-8";
});

const endpoints = computed(() => {
  return router.options.routes
    .filter((r) => r.meta && r.meta.navbar)
    .map((r) => {
      return {
        // never undefined, filter above
        name: r.meta?.name,
        icon: r.meta?.icon,
        path: r.path,
      };
    });
});
</script>

<template>
  <!-- Mobile navigation popover -->
  <transition
    enter-active-class="transition duration-100 ease-out"
    enter-from-class="-translate-y-4 opacity-0"
    enter-to-class="translate-y-0 opacity-100"
    leave-active-class="transition duration-150 ease-in"
    leave-from-class="translate-y-0 opacity-100"
    leave-to-class="-translate-y-4 opacity-0"
  >
    <aside
      v-show="isOpen"
      :class="firefoxMarginBottomClass"
      class="fixed lg:hidden select-none mr-4 bottom-0 right-0 z-20"
    >
      <div
        class="bg-neutral-100 dark:bg-dark-900 box-border border border-neutral-200 dark:border-dark-200/20 rounded-lg p-2"
        ref="popover"
      >
        <div class="flex flex-col gap-y-2 text-lg font-semibold">
          <div
            @click="toggleDark()"
            class="px-3 py-2 border-b border-neutral-200 dark:border-dark-200/10 cursor-pointer"
          >
            <div class="flex flex-row items-center gap-x-2">
              <div class="flex-grow text-right">{{ isDark ? "Light" : "Dark" }}</div>
              <div>
                <component :is="isDark ? SunIcon : MoonIcon" class="w-6 h-6" />
              </div>
            </div>
          </div>

          <NuxtLink
            v-for="endpoint in [...endpoints].reverse()"
            :key="endpoint.name"
            :to="endpoint.path"
            class="px-3 py-2 rounded-lg"
            active-class="bg-primary-600 text-white shadow-sm shadow-primary-300/50"
          >
            <div class="flex flex-row items-center gap-x-2">
              <div class="flex-grow text-right">
                {{ endpoint.name }}
              </div>
              <div>
                <component :is="endpoint.icon" class="w-6 h-6" />
              </div>
            </div>
          </NuxtLink>

          <div
            @click="isOpen = false"
            class="px-3 py-2 border-t border-neutral-200 dark:border-dark-200/10 cursor-pointer"
          >
            <div class="flex flex-row items-center gap-x-2">
              <div class="flex-grow text-right">Close</div>
              <div>
                <x-icon class="w-6 h-6" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </aside>
  </transition>

  <!-- Mobile navigation menu button -->
  <transition
    enter-active-class="transition duration-100 ease-out"
    enter-from-class="-translate-y-2 opacity-0"
    enter-to-class="translate-y-0 opacity-100"
    leave-active-class="transition duration-150 ease-in"
    leave-from-class="translate-y-0 opacity-100"
    leave-to-class="-translate-y-2 opacity-0"
  >
    <aside
      v-show="!isOpen"
      class="fixed lg:hidden select-none rounded-lg dark:text-dark-200/50 bg-neutral-100 dark:bg-dark-900 box-border border border-neutral-200 dark:border-neutral-200/10 shadow-lg cursor-pointer mr-4 bottom-0 right-0 z-10"
      :class="firefoxMarginBottomClass"
      @click="isOpen = true"
    >
      <MenuIcon class="w-6 h-6 m-3" />
    </aside>
  </transition>

  <!-- Desktop Sidebard -->
  <aside
    data-description="Desktop Sidebar Navigation"
    class="sidebar hidden lg:flex flex-col w-64 border-r border-neutral-200 dark:border-neutral-200/10 dark:bg-neutral-800 bg-white h-full"
  >
    <div class="flex flex-col gap-y-2 sticky top-0 p-4 w-full">
      <div class="self-center py-4 mb-2 border-b border-neutral-200 dark:border-dark-200/10">
        <h1 class="font-extrabold text-xl">GENSHIN.ZENLESS</h1>
      </div>

      <NuxtLink
        v-for="endpoint in endpoints"
        :key="endpoint.name"
        :to="endpoint.path"
        class="w-full flex flex-row items-center gap-x-2 px-3 py-2 font-semibold text-lg cursor-pointer"
        active-class="!bg-primary-600 rounded-tl-md rounded-tr-2xl rounded-bl-2xl rounded-br-md text-white"
      >
        <component :is="endpoint.icon" class="h-7 w-7 p-0" />
        <h1>{{ endpoint.name }}</h1>
      </NuxtLink>
    </div>

    <div class="fixed bottom-4 left-4">
      <div
        @click="toggleDark()"
        class="transition-all duration-75 bg-neutral-200 dark:bg-dark-800 dark:text-neutral-300 rounded-lg flex items-center justify-center aspect-square h-8 cursor-pointer"
      >
        <component :is="isDark ? SunIcon : MoonIcon" class="w-5 h-5" />
      </div>
    </div>
  </aside>
</template>
