// pages/characters/index.vue
<template>
  <MainContainer>
    <h1 class="font-semibold text-4xl mb-4 mt-6">Characters</h1>

    <div class="flex flex-row flex-wrap gap-2 justify-evenly md:justify-start">
      <CardsCharacter
        v-for="character in charactersArray"
        :id="character.id"
        :key="character.id"
        :name="character.name"
        :rarity="character.rarity"
      />
    </div>
  </MainContainer>
</template>

<script setup lang="ts">
import { charactersArray } from "@/data/characters";
import { StarIcon } from "@heroicons/vue/outline";

definePageMeta({
  name: `Characters`,
  icon: StarIcon,
  navbar: true,
});

useZenlessMeta({
  title: `Characters`,
  description: `List of all playable Genshin Impact characters.`,
});
</script>

// src/pages/characters/index.tsx
import type { NextPage } from "next";
import type { ChangeEvent } from "react";

import { debounce } from "lodash-es";
import { useState } from "react";

import { CharacterCard } from "@/components/cards/CharacterCard";
import { Container } from "@/components/Container";
import { Input } from "@/components/Input";
import { Layout } from "@/components/Layout";
import { charactersArray } from "@/data/characters";

const CharactersIndex: NextPage = () => {
  const [input, setInput] = useState("");

  const deboucnedHandleChange = debounce((e: ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value);
  }, 300);

  return (
    <Layout title="Characters" description="Genshin Impact playable characters.">
      <Container>
        <div className="mb-4 mt-6 flex flex-col lg:flex-row gap-4">
          <h1 className="font-semibold text-4xl">Characters</h1>
          <Input
            placeholder="Search by name"
            onChange={deboucnedHandleChange}
            className="translate-y-1"
          />
        </div>

        <div className="flex flex-row flex-wrap gap-4 justify-evenly md:justify-start">
          {charactersArray
            .filter((character) => character.name.toLowerCase().includes(input.toLowerCase()))
            .map((character) => (
              <CharacterCard key={character.id} character={character} />
            ))}
        </div>
      </Container>
    </Layout>
  );
};

export default CharactersIndex;
