// app/components/Footer.tsx
import type { FC } from "react";

import { useTranslations } from "use-intl";

import { ExternalLink } from "~/components/ExternalLink";
import { DiscordLogo } from "~/components/icons/DiscordLogo";
import { GitHubLogo } from "~/components/icons/GitHubLogo";

export const Footer: FC = () => {
  const t = useTranslations();

  return (
    <footer className="footer border-t border-neutral-200 text-neutral-400 dark:border-neutral-800 dark:text-neutral-600">
      <div className="mx-auto grid w-full max-w-[var(--max-content-width)] grid-cols-1 grid-rows-[auto_auto] border-neutral-400 px-[var(--default-gap)] py-8 text-sm lg:grid-cols-[1fr_auto]">
        <p>
          {t.rich("footer.affiliation", {
            officialWebsite: (children) => (
              <ExternalLink href="https://www.mihoyo.com/">{children}</ExternalLink>
            ),
          })}
          <br />
          {t.rich("footer.copyright", {
            officialWebsite: (children) => (
              <ExternalLink href="https://www.mihoyo.com/">{children}</ExternalLink>
            ),
          })}
        </p>

        <div className="mt-6 flex flex-col gap-x-6 gap-y-2 place-self-start font-bold lg:mt-0 lg:flex-row lg:place-self-center">
          <ExternalLink href="https://github.com/kitsune-guuji/gvp">
            <div className="flex flex-row items-center gap-x-2">
              <GitHubLogo className="inline-block h-auto w-4" />
              <p>GitHub</p>
            </div>
          </ExternalLink>

          <ExternalLink href="https://discord.gg/TgyFNhthCK">
            <div className="flex flex-row items-center gap-x-2">
              <DiscordLogo className="inline-block h-auto w-4" />
              <p>Discord</p>
            </div>
          </ExternalLink>
        </div>
      </div>
    </footer>
  );
};

// src/components/Footer.vue
<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts">
import DiscordLogo from "@/components/icons/DiscordLogo.vue";
import GitHubLogo from "@/components/icons/GitHubLogo.vue";
</script>

<template>
  <footer
    class="footer grid grid-cols-1 lg:grid-cols-[1fr_auto] grid-rows-[auto_auto] lg:grid-rows-1 py-4 mx-4 text-neutral-400 dark:text-dark-600 border-t border-neutral-200 dark:border-neutral-200/10"
  >
    <p>
      genshin.zenless.club is not affiliated with
      <a
        class="hover:text-primary-500 transition-colors ease-in-out duration-200"
        target="_blank"
        href="https://www.mihoyo.com/"
        >miHoYo</a
      >. <br />
      All in-game content is the property of
      <a
        class="hover:text-primary-500 transition-colors ease-in-out duration-200"
        target="_blank"
        href="https://www.mihoyo.com/"
        >miHoYo Co., Ltd</a
      >.
    </p>

    <div
      class="place-self-start lg:place-self-center flex flex-col lg:flex-row gap-x-6 gap-y-2 mt-6 lg:mt-0 font-bold"
    >
      <a
        href="https://github.com/kitsune-guuji/gvp"
        target="_blank"
        class="hover:text-primary-500 ransition-colors ease-in-out duration-200"
      >
        <div class="flex flex-row gap-x-2 items-center">
          <GitHubLogo class="w-4 h-auto inline-block" />
          <p>GitHub</p>
        </div>
      </a>

      <a
        href="https://discord.gg/TgyFNhthCK"
        class="hover:text-primary-500 transition-colors ease-in-out duration-200"
      >
        <div class="flex flex-row gap-x-2 items-center">
          <DiscordLogo class="w-4 h-auto inline-block" />
          <p>Discord</p>
        </div>
      </a>
    </div>
  </footer>
</template>
