// components/Navigation.tsx
import { useRouter } from "next/router";
import NextLink from "next/link";
import { BeakerIcon, CalculatorIcon, HomeIcon, StarIcon } from "@heroicons/react/outline";
import { MenuIcon, SunIcon, MoonIcon, XIcon } from "@heroicons/react/solid";
import { FC, Fragment, type ReactNode, useEffect, useRef, useState, useCallback } from "react";
import { useClickAway } from "react-use";
import { useTheme } from "next-themes";

interface NavRoute {
  path: string;
  title: string;
  hasNested?: boolean;
  icon: ReactNode;
}

const navRoutes: NavRoute[] = [
  {
    path: "/",
    title: "Home",
    icon: <HomeIcon className="h-7 w-7 p-0" />,
  },
  {
    path: "/characters",
    title: "Characters",
    hasNested: true,
    icon: <StarIcon className="h-7 w-7 p-0" />,
  },
  {
    path: "/guides",
    title: "Guides",
    hasNested: true,
    icon: <BeakerIcon className="h-7 w-7 p-0" />,
  },
  {
    path: "/calc",
    title: "Calculator",
    icon: <CalculatorIcon className="h-7 w-7 p-0" />,
  },
];

export const Navigation: FC = () => {
  const router = useRouter();

  const [isMounted, setMounted] = useState(false);
  const { theme, setTheme, resolvedTheme } = useTheme();

  const toggleDark = () => {
    // don't do anything unless it's client side
    if (!isMounted) return;

    if (resolvedTheme === "dark" && theme === "system") {
      setTheme("light");
    } else if (resolvedTheme === "light" && theme === "system") {
      setTheme("dark");
    } else {
      setTheme("system");
    }
  };

  useEffect(() => {
    setMounted(true);
  }, []);

  const [isOpen, setOpen] = useState(false);
  const popoverRef = useRef(null);

  const openPopever = () => {
    setOpen(true);
  };

  const closePopover = () => {
    setOpen(false);
  };

  useClickAway(popoverRef, () => {
    closePopover();
  });

  const isActive = useCallback(
    (navRoute: NavRoute) => {
      if (navRoute.hasNested === true) {
        return router.route.startsWith(navRoute.path);
      }

      return router.route === navRoute.path;
    },
    [router.route],
  );

  const activeClass = useCallback(
    (navRoute: NavRoute, isMobile: boolean = false) => {
      const active = isActive(navRoute);

      if (isMobile && active) {
        return " bg-primary-600 text-white shadow-sm shadow-primary-300/50";
      } else if (!isMobile && active) {
        return " !bg-primary-600 rounded-tl-md rounded-tr-2xl rounded-bl-2xl rounded-br-md text-white";
      }

      return "";
    },
    [isActive],
  );

  // firefox specific issue
  const mobileMarginBottom =
    isMounted && navigator.userAgent.toLowerCase().includes("firefox") ? "mb-10" : "mb-8";

  return (
    <>
      {/* Mobile Navigation popover */}
      {isOpen && (
        <aside
          className={`fixed lg:hidden select-none mr-4 bottom-0 right-0 z-20 ${mobileMarginBottom}`}
        >
          <div
            className="bg-neutral-100 dark:bg-dark-900 box-border border border-neutral-200 dark:border-dark-200/20 rounded-lg p-2"
            ref={popoverRef}
          >
            <div className="flex flex-col gap-y-2 text-lg font-semibold">
              {isMounted && (
                <div
                  onClick={toggleDark}
                  className="px-3 py-2 border-b border-neutral-200 dark:border-dark-200/10 cursor-pointer"
                >
                  <div className="flex flex-row items-center gap-x-2">
                    <div className="flex-grow text-right">
                      {resolvedTheme === "dark" && "Dark"}
                      {resolvedTheme !== "dark" && "Light"}
                    </div>
                    <div>
                      {resolvedTheme === "dark" && <SunIcon className="w-6 h-6" />}
                      {resolvedTheme !== "dark" && <MoonIcon className="w-6 h-6" />}
                    </div>
                  </div>
                </div>
              )}

              {navRoutes.map((navRoute) => (
                <NextLink key={`${navRoute.title}-popover-item`} href={navRoute.path}>
                  <a className={`px-3 py-2 rounded-lg ${activeClass(navRoute, true)}`}>
                    <div className="flex flex-row items-center gap-x-2">
                      <div className="flex-grow text-right">{navRoute.title}</div>
                      <div>{navRoute.icon}</div>
                    </div>
                  </a>
                </NextLink>
              ))}

              <div
                onClick={() => closePopover()}
                className="px-3 py-2 border-t border-neutral-200 dark:border-dark-200/10 cursor-pointer"
              >
                <div className="flex flex-row items-center gap-x-2">
                  <div className="flex-grow text-right">Close</div>
                  <div>
                    <XIcon className="w-6 h-6" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </aside>
      )}

      {!isOpen && (
        <aside
          onClick={() => openPopever()}
          className={`fixed lg:hidden select-none rounded-lg dark:text-dark-200/50 bg-neutral-100 dark:bg-dark-900 box-border border border-neutral-200 dark:border-neutral-200/10 shadow-lg cursor-pointer mr-4 bottom-0 right-0 z-10 ${mobileMarginBottom}`}
        >
          <MenuIcon className="w-6 h-6 m-3" />
        </aside>
      )}

      {/* Desktop Sidebard */}
      <aside
        data-description="Desktop Sidebar Navigation"
        className="sidebar hidden lg:flex flex-col w-64 border-r border-neutral-200 dark:border-neutral-200/10 dark:bg-neutral-800 bg-white h-full"
      >
        <div className="flex flex-col gap-y-2 sticky top-0 p-4 w-full">
          <div className="self-center py-4 mb-2 border-b border-neutral-200 dark:border-dark-200/10">
            <h1 className="font-extrabold text-xl">GENSHIN.ZENLESS</h1>
          </div>

          {navRoutes.map((navRoute) => (
            <NextLink key={navRoute.path} href={navRoute.path}>
              <a
                className={
                  "w-full flex flex-row items-center gap-x-2 px-3 py-2 font-semibold text-lg cursor-pointer" +
                  activeClass(navRoute)
                }
              >
                <Fragment>{navRoute.icon}</Fragment>
                <h1>{navRoute.title}</h1>
              </a>
            </NextLink>
          ))}
        </div>

        {isMounted && (
          <div className="fixed bottom-4 left-4">
            <div
              onClick={() => toggleDark()}
              className="transition-all duration-75 bg-neutral-200 dark:bg-dark-800 dark:text-neutral-300 rounded-lg flex items-center justify-center aspect-square h-8 cursor-pointer"
            >
              {resolvedTheme === "dark" && <SunIcon className="w-5 h-5" />}
              {resolvedTheme !== "dark" && <MoonIcon className="w-5 h-5" />}
            </div>
          </div>
        )}
      </aside>
    </>
  );
};

// src/components/Navigation.vue
<!-- eslint-disable vue/multi-word-component-names -->
<script setup lang="ts">
import { computed, ref } from "vue";
import { RouterLink, useRouter } from "vue-router";

import { MenuIcon, XIcon } from "@heroicons/vue/outline";
import { MoonIcon, SunIcon } from "@heroicons/vue/solid";
import { onClickOutside } from "@vueuse/core";
import { useDark, useToggle } from "@vueuse/core";

const router = useRouter();

const isOpen = ref(false);
const popover = ref(null);

const isDark = useDark({ storageKey: "theme" });
const toggleDark = useToggle(isDark);

onClickOutside(popover, () => {
  isOpen.value = false;
});

// thanks firefox for being great
const firefoxMarginBottomClass = computed(() => {
  if (navigator.userAgent.toLowerCase().includes("firefox")) {
    return "mb-10";
  }
  return "mb-8";
});

const endpoints = computed(() => {
  return router.options.routes
    .filter((r) => r.meta && r.meta.navigation)
    .map((r) => {
      return {
        // never undefined, filter above
        name: r.meta?.navigation?.name,
        icon: r.meta?.navigation?.icon,
        path: r.path,
      };
    });
});
</script>

<template>
  <!-- Mobile navigation popover -->
  <transition
    enter-active-class="transition duration-100 ease-out"
    enter-from-class="-translate-y-4 opacity-0"
    enter-to-class="translate-y-0 opacity-100"
    leave-active-class="transition duration-150 ease-in"
    leave-from-class="translate-y-0 opacity-100"
    leave-to-class="-translate-y-4 opacity-0"
  >
    <aside
      v-show="isOpen"
      :class="firefoxMarginBottomClass"
      class="fixed lg:hidden select-none mr-4 bottom-0 right-0 z-20"
    >
      <div
        class="bg-neutral-100 dark:bg-dark-900 box-border border border-neutral-200 dark:border-dark-200/20 rounded-lg p-2"
        ref="popover"
      >
        <div class="flex flex-col gap-y-2 text-lg font-semibold">
          <div
            @click="toggleDark()"
            class="px-3 py-2 border-b border-neutral-200 dark:border-dark-200/10 cursor-pointer"
          >
            <div class="flex flex-row items-center gap-x-2">
              <div class="flex-grow text-right">{{ isDark ? "Light" : "Dark" }}</div>
              <div>
                <component :is="isDark ? SunIcon : MoonIcon" class="w-6 h-6" />
              </div>
            </div>
          </div>

          <RouterLink
            v-for="endpoint in [...endpoints].reverse()"
            :key="endpoint.name"
            :to="endpoint.path"
            class="px-3 py-2 rounded-lg"
            active-class="bg-primary-600 text-white shadow-sm shadow-primary-300/50"
          >
            <div class="flex flex-row items-center gap-x-2">
              <div class="flex-grow text-right">
                {{ endpoint.name }}
              </div>
              <div>
                <component :is="endpoint.icon" class="w-6 h-6" />
              </div>
            </div>
          </RouterLink>

          <div
            @click="isOpen = false"
            class="px-3 py-2 border-t border-neutral-200 dark:border-dark-200/10 cursor-pointer"
          >
            <div class="flex flex-row items-center gap-x-2">
              <div class="flex-grow text-right">Close</div>
              <div>
                <x-icon class="w-6 h-6" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </aside>
  </transition>

  <!-- Mobile navigation menu button -->
  <transition
    enter-active-class="transition duration-100 ease-out"
    enter-from-class="-translate-y-2 opacity-0"
    enter-to-class="translate-y-0 opacity-100"
    leave-active-class="transition duration-150 ease-in"
    leave-from-class="translate-y-0 opacity-100"
    leave-to-class="-translate-y-2 opacity-0"
  >
    <aside
      v-show="!isOpen"
      class="fixed lg:hidden select-none rounded-lg dark:text-dark-200/50 bg-neutral-100 dark:bg-dark-900 box-border border border-neutral-200 dark:border-neutral-200/10 shadow-lg cursor-pointer mr-4 bottom-0 right-0 z-10"
      :class="firefoxMarginBottomClass"
      @click="isOpen = true"
    >
      <MenuIcon class="w-6 h-6 m-3" />
    </aside>
  </transition>

  <!-- Desktop Sidebard -->
  <aside
    data-description="Desktop Sidebar Navigation"
    class="sidebar hidden lg:flex flex-col w-64 border-r border-neutral-200 dark:border-dark-200/10 dark:bg-neutral-950 bg-white h-full"
  >
    <div class="flex flex-col gap-y-2 sticky top-0 p-4 w-full">
      <div class="self-center py-4 mb-2 border-b border-neutral-200 dark:border-dark-200/10">
        <h1 class="font-extrabold text-xl">GENSHIN.ZENLESS</h1>
      </div>

      <RouterLink
        v-for="endpoint in endpoints"
        :key="endpoint.name"
        :to="endpoint.path"
        class="w-full flex flex-row items-center gap-x-2 px-3 py-2 font-semibold text-lg cursor-pointer"
        active-class="!bg-primary-600 rounded-tl-md rounded-tr-2xl rounded-bl-2xl rounded-br-md text-white"
      >
        <component :is="endpoint.icon" class="h-7 w-7 p-0" />
        <h1>{{ endpoint.name }}</h1>
      </RouterLink>
    </div>

    <div class="fixed bottom-4 left-4">
      <div
        @click="toggleDark()"
        class="transition-all duration-75 bg-neutral-200 dark:bg-dark-900 dark:text-neutral-300 rounded-lg flex items-center justify-center aspect-square h-8 cursor-pointer"
      >
        <component :is="isDark ? SunIcon : MoonIcon" class="w-5 h-5" />
      </div>
    </div>
  </aside>
</template>
