// src/pages/calc.tsx
import dayjs from "dayjs";
import { useState } from "react";

import { CalculatorDetails } from "@/components/calculator/CalculatorDetails";
import { CalculatorInput } from "@/components/calculator/CalculatorInput";
import { CalculatorResult } from "@/components/calculator/CalculatorResult";
import { CalculatorRoot } from "@/components/calculator/CalculatorRoot";
import { CalculatorTitle } from "@/components/calculator/CalculatorTitle";
import { Container } from "@/components/Container";
import { Layout } from "@/components/Layout";

const CalcPage = () => {
  const [critRate, setCritRate] = useState(NaN);
  const [critDmg, setCritDmg] = useState(NaN);
  const critValue = critDmg + critRate * 2;

  const [resinCurrent, setResinCurrent] = useState(NaN);
  const [resinNeeded, setResinNeeded] = useState(NaN);
  const resinDelta = (resinNeeded - resinCurrent) * 8;
  const resinReplenishAt = dayjs().add(resinDelta, `minutes`);

  return (
    <Layout
      title="Calculators"
      description="Genshin Impact calculators for crti value, resin and etc."
    >
      <Container>
        <div className="columns-1 md:columns-2 gap-4 space-y-4">
          <CalculatorRoot className="overflow-y-auto break-inside-avoid">
            <CalculatorTitle>Crit Value</CalculatorTitle>
            <CalculatorDetails>Provide your stats details</CalculatorDetails>
            <CalculatorInput setValue={setCritRate} step={0.1} placeholder="Artifact's crit rate" />
            <CalculatorInput
              setValue={setCritDmg}
              step={0.1}
              placeholder="Artifact's crit damage"
            />

            {critRate > 0 && critDmg > 0 && (
              <CalculatorResult>
                Crit Value is{` `}
                <span className="text-primary-500 dark:text-primary-400 font-semibold">
                  {critValue}
                </span>
              </CalculatorResult>
            )}
          </CalculatorRoot>

          <CalculatorRoot className="overflow-y-auto break-inside-avoid">
            <CalculatorTitle>Resin</CalculatorTitle>
            <CalculatorDetails>Find out when you&apos;ll be able to farm</CalculatorDetails>
            <CalculatorInput setValue={setResinCurrent} placeholder="How much resin you have" />
            <CalculatorInput setValue={setResinNeeded} placeholder="How much resin you need" />

            {resinDelta > 0 && (
              <CalculatorResult>
                You will have{` `}
                <span className="text-primary-500 dark:text-primary-400 font-semibold">
                  {resinNeeded}
                </span>
                {` `}
                at{` `}
                <span className="text-primary-500 dark:text-primary-400 font-semibold">
                  {resinReplenishAt.format(`lll`)}
                </span>
              </CalculatorResult>
            )}
          </CalculatorRoot>
        </div>
      </Container>
    </Layout>
  );
};

export default CalcPage;

// pages/calc.vue
<template>
  <MainContainer>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 lg:gap-6">
      <div>
        <CalculatorRoot id="crit-value">
          <CalculatorTitle>Crit Value</CalculatorTitle>
          <CalculatorDetails>Provide your stats details</CalculatorDetails>
          <CalculatorInput
            v-model="critRate"
            type="number"
            :step="0.1"
            placeholder="Artifact's crit rate"
          />
          <CalculatorInput
            v-model="critDamage"
            type="number"
            :step="0.1"
            placeholder="Artifact's crit damage"
          />
          <CalculatorResult v-if="!isNil(critValue)">
            Crit Value is <span class="text-primary-500 font-semibold">{{ critValue }}</span>
          </CalculatorResult>
        </CalculatorRoot>
      </div>

      <div>
        <CalculatorRoot id="resin">
          <CalculatorTitle>Resin Refill</CalculatorTitle>
          <CalculatorInput
            v-model="resinCurrent"
            type="number"
            placeholder="How much resin you currently have"
          />
          <CalculatorInput
            v-model="resinNeeded"
            type="number"
            placeholder="How much resin you need"
          />
          <CalculatorResult v-if="!isNil(fullResinAt)">
            You will have <span class="text-primary-500 font-semibold">{{ resinNeeded }}</span> on
            <span class="text-primary-500 font-semibold">{{ fullResinAt }}</span>
          </CalculatorResult>
        </CalculatorRoot>
      </div>
    </div>
  </MainContainer>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import { isNil, isNumber } from "lodash-es";

import { CalculatorIcon } from "@heroicons/vue/outline";

definePageMeta({
  name: `Calculate`,
  icon: CalculatorIcon,
  navbar: true,
});

const { $dayjs } = useNuxtApp();

const critRate = ref<number | undefined>(undefined);
const critDamage = ref<number | undefined>(undefined);

const critValue = computed(() => {
  if (!isNumber(critRate.value) || !isNumber(critDamage.value)) {
    return null;
  }

  return critDamage.value + critRate.value * 2;
});

const resinCurrent = ref<number | undefined>(undefined);
const resinNeeded = ref<number | undefined>(undefined);

const fullResinAt = computed(() => {
  if (!isNumber(resinCurrent.value) || !isNumber(resinNeeded.value)) {
    return null;
  }

  const delta = resinNeeded.value - resinCurrent.value;
  const minutesToWait = delta * 8;
  const refillsAt = $dayjs().add(minutesToWait, `minutes`);

  return refillsAt.format(`LLL`);
});

useZenlessMeta({
  title: `Calculators`,
  description: `Genshin Impact calculators such as crit value, resin, etc.`,
});
</script>
