// pages/index.vue
<template>
  <MainContainer :vertical-center="true">
    <div class="flex flex-col items-center">
      <h1 class="font-bold text-4xl">Hello, user!</h1>
      <p>Welcome to genshin.zenless.club!</p>
    </div>
  </MainContainer>
</template>

<script setup lang="ts">
import { HomeIcon } from "@heroicons/vue/outline";

definePageMeta({
  name: `Home`,
  icon: HomeIcon,
  navbar: true,
});

useZenlessMeta({
  title: `Home`,
  description: `A place for Genshin Impact character guides, calculators and other utilities`,
});
</script>

// pages/index.tsx
import type { NextPage } from "next";

import { Container } from "@/components/Container";
import { Layout } from "@/components/Layout";

const Home: NextPage = () => {
  return (
    <Layout
      title="Home"
      description="Genshin Impact characters data, calculators, playstyle guides and more!"
    >
      <Container verticalCenter>
        <div className="flex flex-col items-center">
          <h1 className="font-bold text-4xl">Hello, user!</h1>
          <p>Welcome to genshin.zenless.club!</p>
        </div>
      </Container>
    </Layout>
  );
};

export default Home;
