// components/calculator/CalculatorInput.tsx
import { ChangeEvent, FC } from "react";

interface Props {
  setValue: (value: number) => void;
  placeholder?: string;
  step?: number;
  className?: string;
}

export const CalculatorInput: FC<Props> = ({
  setValue,
  placeholder,
  step = 0.1,
  className = "",
}) => {
  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setValue(e.target.valueAsNumber);
  };

  return (
    <input
      type="number"
      step={step}
      placeholder={placeholder}
      onChange={handleChange}
      className={`calculator-input ${className}`}
    />
  );
};

// src/components/Calculators/CalculatorInput.vue
<script setup lang="ts">
import { computed } from "vue";

interface Props {
  modelValue?: number;
  placeholder?: string;
  type?: string;
  step?: number;
}

const props = defineProps<Props>();
const emit = defineEmits(["update:modelValue"]);

const value = computed({
  get() {
    return props.modelValue;
  },
  set(value) {
    emit("update:modelValue", value);
  },
});
</script>

<template>
  <input
    v-model="value"
    :type="type"
    :step="step"
    :placeholder="placeholder"
    class="calculator-input"
  />
</template>
